# Setup
title: Croot Blog
tagnline: tagline area
description: >- # this means to ignore newlines until "baseurl:"
  private blog site.
url: "https://croot-dev.github.io/"
repository: https://github.com/croot-dev/croot-dev.github.io
baseurl: ""
permalink: pretty
pagination:
    enabled: true
    per_page: 10
    limit: 0
    sort_field: "date"
    sort_reverse: true

# About/contact
author:
  name: Croot
  url: https://croot-dev.github.io
  email: croot-dev@gmail.com
github:
  repo: https://github.com/croot-dev/croot-dev.github.io

# Build settings
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
