# Setup
title: Croot Blog
tagnline: tagline area
description: >- # this means to ignore newlines until "baseurl:"
  private blog site.
url: "https://croot-dev.github.io/"
user: croot-dev
baseurl: ""

permalink: pretty
pagination:
  enabled: true
  per_page: 10
  limit: 0
  sort_field: "date"
  sort_reverse: true
  trail: 
      before: 2
      after: 2
autopages:
  enabled: false

include: [_pages]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
exclude: [vendor]

# About/contact
author:
  name: Croot
  domain: croot-dev.github.io
  email: croot-dev@gmail.com
github_username: croot-dev

# Build settings
plugins:
  - jekyll-paginate
  